name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 */12 * * *'  # This cron expression will run every 12 hours.
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Supabase
        run: |
          curl -X GET "https://rjptmnillqlavugrmvvt.supabase.co/rest/v1/keepalive" \
            -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
